name: accname ED
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'accname/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to accname repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ARIA_EDITOR_DRAFTS}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/daniel-montalvo/accname/actions/workflows/build-from-monorepo.yaml/dispatches \
          -d '{"ref":"gh-pages"}'
  update-accname:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          ref: main
          path: aria
          sparse-checkout: |
            accname
            common
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/accname/index.html
          DESTINATION: aria/accname/index.html
          ARTIFACT_NAME: accname
      - name: Checkout accname repo
        uses: actions/checkout@v4
        with:
          repository: daniel-montalvo/accname
          ref: gh-pages
          path: accname
          token: ${{ secrets.ARIA_EDITOR_DRAFTS }}
      - uses: actions/download-artifact@v4
        with:
          name: accname
          path: accname/
    #   - name: Copy files
    #     run: |
    #       cp -r aria/common accname
    #       cp -r aria/accname .
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from monorepo"
          git push origin gh-pages
        working-directory: accname
