name: dpub-aam ED
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'dpub-aam/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to dpub-aam repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ARIA_EDITOR_DRAFTS}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/daniel-montalvo/dpub-aam/actions/workflows/build-from-monorepo.yaml/dispatches \
          -d '{"ref":"gh-pages"}'
  update-dpub-aam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          ref: main
          path: aria
          sparse-checkout: |
            dpub-aam
            common
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/dpub-aam/index.html
          DESTINATION: aria/dpub-aam/index.html
          ARTIFACT_NAME: dpub-aam
      - name: Checkout dpub-aam repo
        uses: actions/checkout@v4
        with:
          repository: daniel-montalvo/dpub-aam
          ref: gh-pages
          path: dpub-aam
          token: ${{ secrets.ARIA_EDITOR_ }}
      - uses: actions/download-artifact@v4
        with:
          name: dpub-aam
          path: dpub-aam/
    #   - name: Copy files
    #     run: |
    #       cp -r aria/common dpub-aam
    #       cp -r aria/dpub-aam .
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from monorepo"
          git push origin gh-pages
        working-directory: dpub-aam
