name: Lightweight check on pull requests

# See https://github.com/w3c/spec-prod/blob/main/docs/examples.md#deploy-to-github-pages

on:
  pull_request: {}
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source:
            - index.html
            - core-aam/index.html
            - accname/index.html
            - dpub-aam/index.html
            - dpub-aria/index.html
            - graphics-aam/index.html
            - graphics-aria/index.html
            - svg-aam/index.html 
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          TOOLCHAIN: respec
          BUILD_FAIL_ON: nothing
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
