name: mathml-aam Validation
on:
  pull_request:
    paths:
      - 'common/**'
      - 'mathml-aam/**'
  workflow_dispatch:

jobs:
  validate-mathml-aam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          ref: main
          path: aria
          sparse-checkout: |
            mathml-aam
            common
      - name: Copy common
        run: |
          mkdir aria/mathml-aam/common
          cp -r aria/common/** aria/mathml-aam/common/    
          sed -i 's|\.\./common|common|g' aria/mathml-aam/index.html
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/mathml-aam/index.html
          DESTINATION: aria/mathml-aam/index.html
          BUILD_FAIL_ON: fatal
          VALIDATE_WEBIDL: true
          VALIDATE_LINKS: true
          VALIDATE_MARKUP: true